[versions]
agp = "8.11.0"
androidx-preference = "1.2.1"
kotlin = "2.2.0"
kotlinCoroutinesVersion = "1.10.2"
junit = "4.13.2"
androidx-test-ext-junit = "1.2.1"
google-truth = "1.4.4"
roboelectric = "4.15.1"
timber = "5.0.1"

[libraries]
# AndroidX
androidx-preference = { module = "androidx.preference:preference", version.ref = "androidx-preference" }

# Kotlinx
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinCoroutinesVersion" }

# Tests
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
google-truth = { module = "com.google.truth:truth", version.ref = "google-truth" }
roboelectric = { module = "org.robolectric:robolectric", version.ref = "roboelectric" }

timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[bundles]

