name: Android CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Build and test
        run: ./gradlew test assembleRelease

      - name: Uploading artifacts
        uses: actions/upload-artifact@v3
        with:
          name: apks
          path: ${{ github.workspace }}/**/build/outputs/apk/**/*.apk
          if-no-files-found: error